// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUyZ3mxrGPB_QnQD5cUUCn0cXjHfuVRk',
    appId: '1:1018036668126:web:f9017661c6ed1650ed244f',
    messagingSenderId: '1018036668126',
    projectId: 'fir-messaging-alura',
    authDomain: 'fir-messaging-alura.firebaseapp.com',
    storageBucket: 'fir-messaging-alura.appspot.com',
    measurementId: 'G-RJ3E5C2KVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78su1FTksZTvYx7H56RuI2hIJtt2jRZs',
    appId: '1:1018036668126:android:f9e28a8b36c6c710ed244f',
    messagingSenderId: '1018036668126',
    projectId: 'fir-messaging-alura',
    storageBucket: 'fir-messaging-alura.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_w8w-SOjkQ1arMyIo1MrZ3P6uIPMvb7w',
    appId: '1:1018036668126:ios:89572127aa561f60ed244f',
    messagingSenderId: '1018036668126',
    projectId: 'fir-messaging-alura',
    storageBucket: 'fir-messaging-alura.appspot.com',
    iosBundleId: 'br.com.alura.devMeetups',
  );
}
